- name: installing mysql-server
  hosts: mysql
  become: yes
  tasks:
  - name: installing mysql-server
    ansible.builtin.package:
         name: mysql-server
         state: present
  - name: strting and enabling mysql
    ansible.builtin.service:
         name: mysqld
         state: started
         enabled: yes
  
  - name: connecting to mysql-server
    community.mysql.mysql_info:
      login_user: root
      login_password: DevOps321
      login_host: mysql.daws17s.online
    
    register: mysql_info
  

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ mysql_info }}"