- name: inatlling mysql-server
  hosts: mysql
  become: yes
  vars:
    mysql_root_pass: ExpenseApp@1
  tasks:
  - name: installing mysql-server
    ansible.builtin.package:
       name: mysql-server
       state: installed
  - name: enable and start mysqld
    ansible.builtin.service:
        name: mysqld
        enabled: yes
        state: started
  - name: connecting mysql db
    community.mysql.mysql_info:
       login_user: root
       login_password: "{{ mysql_root_pass }}"
       login_host: mysql.daws17s.online
    register: mysql_info
    ignore_errors: true


  - name: print the output
    ansible.builtin.debug:
      msg: "{{ mysql_info }}"

  - name: setting up the root login_password
    ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ mysql_root_pass}}"
    when: mysql_info.failed is true

 